### ISSUE TITLE
Attributes used in example

### ISSUE THREAD

**Issue by StefanDumont** [hou2zi0/tei-doc-link#2]
The tool is excellent and the example of course very nicely chosen. However, the example contains two small errors: @sex is not allowed for persName (person only) and correspAction/@type linked to att.type although there is specialized documentation for @type in correspAction (with specially proposed values). Maybe it is worth to adjust this? With correspAction/@type it gets a bit tricky to distinguish this from the normal @type. I admit that ;-)

**Comment by hou2zi0** [comment]
Thanks for the corrections! I am going to fix the @sex attributes this evening. I want to implement more context sensitivity regarding attributes in the future (see To Do). I decided, however, to first implement the linking to the more “generic” parts of the documentation (I already have some ideas how to implement more context sensitivity, though).

**Comment by hou2zi0** [comment]
I fixed the attributes issue. I also am working on implementing the context sensitivity (it’s in the To Dos now), therefore I’ll close this issue.
