### ISSUE TITLE
Fix hyphen vs underscore inconsistencies

### ISSUE THREAD

**Issue by awagner-mainz** [hou2zi0/tei-doc-link#4]
Css class names are like span.comment-string and a.tei-doc-link (with hyphens), but they are also like span.line_numbering and span.code_line (with underscores).

I think this might be on the Todo list anyway and it's not a high priority - for me, it's definitely not -, but here's a ticket for it.

Thumbs-up for the whole thing, by the way!

**Comment by hou2zi0** [comment]
Changed the underscores to dashes. Thanks for the info!
